# Building a Document-Term Matrix from scratch


In [ ]:
# install & import the libraries needed
# !pip3 install pandas
# !pip3 install scikit-learn
from typing import List
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
# A mini corpus to play with
CORPUS = [
    'this is the first document',
    'this is the second document',
    'and this is the third document',
    'is this the first document ?'
]

In [ ]:
def tf(corpus: str, voca: str):
    ### TODO 1 ### 
    # count the frequency of term in doc. hint: str.count()
    tf = []
    for i in corpus:
      ltf = []
      for j in voca:
        ltf.append(i.count(j))
      tf.append(ltf)
    ##############
    return tf

In [ ]:
tf(CORPUS, vocab)

[[1, 1, 0, 0, 0, 0, 1, 2, 1],
 [1, 0, 0, 0, 1, 0, 1, 2, 1],
 [1, 0, 0, 1, 0, 1, 1, 2, 1],
 [1, 1, 1, 0, 0, 0, 1, 2, 1]]

In [ ]:
vocab

['the', 'first', '?', 'and', 'second', 'third', 'this', 'is', 'document']

In [ ]:
def build_dtm(corpus: List[str]) -> pd.DataFrame:
    ### TODO 2 ###
    # build a vocabulary of the given corpus - use nested list comprehension, str.split(" "),  set,  and list
    vocab: List[str] = list(set(sent for row in CORPUS for sent in row.split(" ")))
    ##############

    ### TODO 3 ###
    # populate a dtm - get use of the tf function
    dtm: List[List[int]] = tf(CORPUS, vocab)
    ##############
    # return dtm as a pandas dataframe (for better visualization of the columns)
    dtm = pd.DataFrame(data=dtm, columns=vocab)
    return dtm

In [ ]:
 # build a dtm from the corpus, and have a look at it
dtm = build_dtm(CORPUS)
print(dtm)

   the  first  ?  and  second  third  this  is  document
0    1      1  0    0       0      0     1   2         1
1    1      0  0    0       1      0     1   2         1
2    1      0  0    1       0      1     1   2         1
3    1      1  1    0       0      0     1   2         1


다음과 같은 결과가 나와야 합니다 (단어의 순서는 달라도 괜찮습니다):
```
   is  ?  first  and  document  this  the  second  third
0   2  0      1    0         1     1    1       0      0
1   2  0      0    0         1     1    1       1      0
2   2  0      0    1         1     1    1       0      1
3   2  1      1    0         1     1    1       0      0
```
(슬라이드에는 0또는 1로 카운트를 했지만, 튜토리얼에서는 그냥 카운트를 하겠습니다! (e.g. is가 두 개 포함되어 있다면 그냥 2로)

In [ ]:
# this will print out the similarities of the documents to each other
sim_matrix = cosine_similarity(dtm.to_numpy(), dtm.to_numpy())
print(sim_matrix)

[[1.         0.875      0.82495791 0.94280904]
 [0.875      1.         0.82495791 0.82495791]
 [0.82495791 0.82495791 1.         0.77777778]
 [0.94280904 0.82495791 0.77777778 1.        ]]


다음과 같은 결과가 나와야 합니다:
```
[[1.         0.875      0.82495791 0.94280904]
 [0.875      1.         0.82495791 0.82495791]
 [0.82495791 0.82495791 1.         0.77777778]
 [0.94280904 0.82495791 0.77777778 1.        ]]
```

## **TODO 4**: 마지막으로, 다음의 질문에 답해주세요.
> 위 `sim_matrix`를 보고 `dtm`의 어떤 문제를 발견할 수 있나요? (힌트: `CORPUS`에 있는 문장의 의미는 모두 동일한가요?)